import type { FastifyInstance } from 'fastify';
import { z } from 'zod';
import { prisma } from '../lib/prisma.js';
import { checkResets, checkAndDeduct, refundCaspers, resolveVideoRequestType } from '../services/tokens.js';
import { visionQueue, soundQueue, reelQueue } from '../lib/bullmq.js';
import { getMediaCached } from '../services/cache.js';
import { checkGenRateLimit, checkVideoRateLimit } from '../services/user-limiter.js';
import { generateLipSync } from '../services/providers/goapi.js';
import { callCloudflareJSON } from '../services/providers/cloudflare.js';
import { encrypt } from '../lib/crypto.js';
import { notifyApiError } from '../services/admin-notify.js';
import crypto from 'crypto';

const generateSchema = z.object({
  prompt: z.string().min(1).max(2000),
  chatId: z.string().optional(),
  style: z.string().optional(),
  duration: z.number().int().min(5).max(30).optional(),
  size: z.enum(['1024x1024', '1792x1024', '1024x1792']).optional(),
  sourceImageUrl: z.string().url().optional(), // for image editing mode
  // Video-specific options
  // motion = Veo 3.1 Fast, cinema = Veo 3.1 Pro, reality = Kling V-2.5
  videoModel: z.enum(['standard', 'pro', 'motion', 'cinema', 'reality']).optional(),
  videoDuration: z.enum(['4s', '8s']).optional(),
  videoAspectRatio: z.enum(['16:9', '9:16']).optional(),
  videoEnableAudio: z.boolean().optional(),
  videoResolution: z.enum(['720p', '1080p']).optional(),
  videoImageUrl: z.string().url().optional(), // image-to-video source
  negativePrompt: z.string().max(2500).optional(),
  // Music-specific
  musicMode: z.enum(['short', 'long', 'quality', 'suno']).optional(),
  musicDuration: z.number().int().min(15).max(60).optional(),
  lyrics: z.string().max(10000).optional(),
  styleAudio: z.string().url().max(2000).optional(),
  // Suno-specific options
  sunoStyle: z.string().max(200).optional(),
  sunoTitle: z.string().max(100).optional(),
  sunoInstrumental: z.boolean().optional(),
});

/**
 * Simulate generation delay for cache hits so the UI shows loading animation.
 */
function completeCachedJobAfterDelay(
  jobId: string,
  mediaUrl: string,
  delayMs: number,
  chatMsg?: { chatId: string; userId: string; prompt: string; mode: string },
) {
  setTimeout(async () => {
    try {
      await prisma.generateJob.update({
        where: { id: jobId },
        data: { status: 'done', mediaUrl },
      });
      if (chatMsg) {
        await prisma.message.create({
          data: {
            chatId: chatMsg.chatId,
            userId: chatMsg.userId,
            role: 'assistant',
            content: encrypt(chatMsg.prompt),
            mode: chatMsg.mode,
            tokensCost: 0,
            mediaUrl,
          },
        }).catch(() => {});
      }
    } catch {}
  }, delayMs);
}

export default async function generateRoutes(fastify: FastifyInstance) {
  // ── Vision (image generation) ─────────────────────────────────────────────
  fastify.post('/generate/vision', {
    preHandler: [fastify.authenticate],
    handler: async (request, reply) => {
      const { userId } = request.user;
      const { prompt, size, chatId, sourceImageUrl } = generateSchema.parse(request.body);

      // Per-user rate limit (3 images/min)
      if (!await checkGenRateLimit(userId)) {
        return reply.code(429).send({ error: 'Слишком много запросов. Подождите минуту.', code: 'RATE_LIMITED' });
      }

      // Job lock: reject if a vision job is already running for this user
      const activeJob = await prisma.generateJob.findFirst({
        where: { userId, mode: 'vision', status: { in: ['pending', 'processing'] } },
        select: { id: true },
      });
      if (activeJob) {
        return reply.code(409).send({ error: 'Задача уже выполняется. Подождите.', code: 'TASK_IN_PROGRESS', jobId: activeJob.id });
      }

      // Reset counters if period ended
      await checkResets(userId);

      // ── Image cache check ─────────────────────────────────────────────────
      const promptHash = crypto.createHash('sha256').update(prompt.trim().toLowerCase()).digest('hex');

      const userMadeThis = await prisma.userImageRequest.findUnique({
        where: { userId_promptHash: { userId, promptHash } },
      });

      if (!userMadeThis) {
        // Check shared cache (generated by any user)
        const mediaCached = await getMediaCached('vision', prompt);
        if (mediaCached.hit) {
          // Serve from cache — NO deduction
          await prisma.userImageRequest.create({ data: { userId, promptHash } }).catch(() => {});
          if (chatId) {
            await prisma.message.create({
              data: { chatId, userId, role: 'assistant', content: encrypt(prompt), mode: 'vision', tokensCost: 0, mediaUrl: mediaCached.url },
            }).catch(() => {});
          }
          const job = await prisma.generateJob.create({
            data: { userId, mode: 'vision', prompt, status: 'processing' },
          });
          completeCachedJobAfterDelay(job.id, mediaCached.url, 5_000 + Math.random() * 4_000);
          return reply.code(202).send({ jobId: job.id });
        }
      }

      // ── New generation — check limits and deduct ──────────────────────────
      const requestType = sourceImageUrl ? 'image_edit' : 'image_generate';
      try {
        await checkAndDeduct(userId, requestType);
      } catch (err: any) {
        return reply.code(403).send({ error: err.message, code: err.code ?? 'LIMIT_IMAGES' });
      }

      // Save user message to chat history
      if (chatId) {
        await prisma.message.create({
          data: { chatId, userId, role: 'user', content: encrypt(prompt), mode: 'vision', tokensCost: 0, mediaUrl: sourceImageUrl ?? null },
        }).catch((e) => console.error('[generate/vision] Failed to save user message:', e.message));
      }

      const userPlan = await prisma.user.findUnique({ where: { id: userId }, select: { plan: true } });
      const effectiveSize = userPlan?.plan === 'FREE' ? '1024x1024' : (size ?? '1024x1024');

      const job = await prisma.generateJob.create({
        data: { userId, mode: 'vision', prompt },
      });

      const bullJob = await visionQueue.add('generate-image', {
        jobId: job.id,
        userId,
        prompt,
        chatId: chatId ?? null,
        size: effectiveSize,
        ...(sourceImageUrl ? { sourceImageUrl } : {}),
      }).catch(async (err: any) => {
        // Queue error: refund and notify admin
        await refundCaspers(userId, requestType).catch(() => {});
        const userInfo = await prisma.user.findUnique({ where: { id: userId }, select: { name: true } }).catch(() => null);
        notifyApiError({
          userId,
          userName: userInfo?.name,
          operation: 'image_gen',
          error: err.message,
        }).catch(() => {});
        throw err;
      });

      await prisma.generateJob.update({
        where: { id: job.id },
        data: { bullJobId: bullJob.id },
      });

      await prisma.userImageRequest.create({ data: { userId, promptHash } }).catch(() => {});

      return reply.code(202).send({ jobId: job.id });
    },
  });

  // ── Sound (music generation) ──────────────────────────────────────────────
  fastify.post('/generate/sound', {
    preHandler: [fastify.authenticate],
    handler: async (request, reply) => {
      const { userId } = request.user;
      const { prompt, chatId, musicMode, musicDuration, lyrics, styleAudio, sunoStyle, sunoTitle, sunoInstrumental } = generateSchema.parse(request.body);

      // Reset counters if period ended
      await checkResets(userId);

      // Per-user rate limit
      if (!await checkGenRateLimit(userId)) {
        return reply.code(429).send({ error: 'Слишком много запросов. Подождите минуту.', code: 'RATE_LIMITED' });
      }

      // Job lock: reject if a sound job is already running for this user
      const activeJob = await prisma.generateJob.findFirst({
        where: { userId, mode: 'sound', status: { in: ['pending', 'processing'] } },
        select: { id: true },
      });
      if (activeJob) {
        return reply.code(409).send({ error: 'Задача уже выполняется. Подождите.', code: 'TASK_IN_PROGRESS', jobId: activeJob.id });
      }

      // Check music limits and deduct
      try {
        await checkAndDeduct(userId, 'music_generate', 1);
      } catch (err: any) {
        return reply.code(403).send({ error: err.message, code: err.code ?? 'LIMIT_MUSIC' });
      }

      // Check media cache after deducting
      const mediaCached = await getMediaCached('sound', prompt);

      if (mediaCached.hit) {
        const job = await prisma.generateJob.create({
          data: { userId, mode: 'sound', prompt, status: 'processing' },
        });
        completeCachedJobAfterDelay(
          job.id, mediaCached.url, 8_000 + Math.random() * 6_000,
          chatId ? { chatId, userId, prompt, mode: 'sound' } : undefined,
        );
        return reply.code(202).send({ jobId: job.id });
      }

      const job = await prisma.generateJob.create({
        data: { userId, mode: 'sound', prompt },
      });

      const bullJob = await soundQueue.add('generate-music', {
        jobId: job.id,
        userId,
        prompt,
        musicMode: musicMode ?? 'short',
        musicDuration: musicDuration,
        chatId: chatId ?? null,
        lyrics: lyrics,
        styleAudio: styleAudio,
        sunoStyle: sunoStyle,
        sunoTitle: sunoTitle,
        sunoInstrumental: sunoInstrumental,
      }).catch(async (err: any) => {
        await refundCaspers(userId, 'music_generate').catch(() => {});
        const userInfo = await prisma.user.findUnique({ where: { id: userId }, select: { name: true } }).catch(() => null);
        notifyApiError({
          userId,
          userName: userInfo?.name,
          operation: 'music_gen',
          error: err.message,
        }).catch(() => {});
        throw err;
      });

      await prisma.generateJob.update({
        where: { id: job.id },
        data: { bullJobId: bullJob.id },
      });

      return reply.code(202).send({ jobId: job.id });
    },
  });

  // ── Reel (video generation) ───────────────────────────────────────────────
  fastify.post('/generate/reel', {
    preHandler: [fastify.authenticate],
    handler: async (request, reply) => {
      const { userId } = request.user;
      const { prompt, chatId, videoModel, videoDuration, videoAspectRatio, videoEnableAudio, videoResolution, videoImageUrl, negativePrompt } = generateSchema.parse(request.body);

      const effectiveModel = videoModel ?? 'standard';
      const effectiveDuration = videoDuration ?? '8s';
      const videoRequestType = resolveVideoRequestType(effectiveModel, effectiveDuration);

      // Fetch user plan — FREE users get Kling, paid get Veo3.1
      const userRecord = await prisma.user.findUnique({ where: { id: userId }, select: { plan: true } });
      const userPlan = userRecord?.plan ?? 'FREE';

      // Reset counters if period ended
      await checkResets(userId);

      // Per-user video rate limit (1/min)
      if (!await checkVideoRateLimit(userId)) {
        return reply.code(429).send({ error: 'Слишком много запросов. Подождите минуту.', code: 'RATE_LIMITED' });
      }

      // Job lock: reject if a reel job is already running for this user
      const activeJob = await prisma.generateJob.findFirst({
        where: { userId, mode: 'reel', status: { in: ['pending', 'processing'] } },
        select: { id: true },
      });
      if (activeJob) {
        return reply.code(409).send({ error: 'Задача уже выполняется. Подождите.', code: 'TASK_IN_PROGRESS', jobId: activeJob.id });
      }

      // Cache check for text-to-video only (image-to-video skips cache)
      if (!videoImageUrl) {
        const mediaCached = await getMediaCached('reel', prompt);
        if (mediaCached.hit) {
          try {
            await checkAndDeduct(userId, videoRequestType);
          } catch (err: any) {
            return reply.code(403).send({ error: err.message, code: err.code ?? 'LIMIT_VIDEOS' });
          }
          const job = await prisma.generateJob.create({
            data: { userId, mode: 'reel', prompt, status: 'processing' },
          });
          completeCachedJobAfterDelay(
            job.id, mediaCached.url, 10_000 + Math.random() * 8_000,
            chatId ? { chatId, userId, prompt, mode: 'reel' } : undefined,
          );
          return reply.code(202).send({ jobId: job.id });
        }
      }

      // Check limits and deduct
      try {
        await checkAndDeduct(userId, videoRequestType);
      } catch (err: any) {
        return reply.code(403).send({ error: err.message, code: err.code ?? 'LIMIT_VIDEOS' });
      }

      const job = await prisma.generateJob.create({
        data: { userId, mode: 'reel', prompt },
      });

      const bullJob = await reelQueue.add('generate-video', {
        jobId: job.id,
        userId,
        prompt,
        userPlan,
        chatId: chatId ?? null,
        videoModel: effectiveModel,
        duration: effectiveDuration,
        aspectRatio: videoAspectRatio ?? '16:9',
        enableAudio: videoEnableAudio ?? false,
        resolution: videoResolution ?? '720p',
        imageUrl: videoImageUrl ?? null,
        negativePrompt,
      }).catch(async (err: any) => {
        await refundCaspers(userId, videoRequestType).catch(() => {});
        const userInfo = await prisma.user.findUnique({ where: { id: userId }, select: { name: true } }).catch(() => null);
        notifyApiError({
          userId,
          userName: userInfo?.name,
          operation: 'video_gen',
          error: err.message,
          context: `model=${effectiveModel} duration=${effectiveDuration}`,
        }).catch(() => {});
        throw err;
      });

      await prisma.generateJob.update({
        where: { id: job.id },
        data: { bullJobId: bullJob.id },
      });

      return reply.code(202).send({ jobId: job.id });
    },
  });

  // ── Lyrics generator ─────────────────────────────────────────────────────
  fastify.post('/generate/lyrics', {
    preHandler: [fastify.authenticate],
    handler: async (request, reply) => {
      const { topic, style, instrumental } = z.object({
        topic: z.string().min(1).max(300),
        style: z.string().max(100).optional(),
        instrumental: z.boolean().optional(),
      }).parse(request.body);

      if (instrumental) {
        return reply.send({ lyrics: '' });
      }

      const styleHint = style ? ` in ${style} style` : '';
      const systemMsg = `You are a professional songwriter. Write song lyrics${styleHint} about: "${topic}".
Rules:
- 2-3 verses + 1 chorus, total ~12-16 lines
- No section headers like [Verse] or [Chorus]
- No timestamps
- Emotional, vivid imagery
- Match the style/genre if specified
- Respond in the same language as the topic
Return ONLY the lyrics text, nothing else.`;

      try {
        const lyrics = await callCloudflareJSON(
          [{ role: 'user', content: systemMsg }],
          512,
        );
        return reply.send({ lyrics: lyrics.trim() });
      } catch {
        return reply.code(502).send({ error: 'Не удалось сгенерировать текст' });
      }
    },
  });

  // ── Lip Sync ──────────────────────────────────────────────────────────────
  fastify.post('/generate/lipsync', {
    preHandler: [fastify.authenticate],
    handler: async (request, reply) => {
      const { userId } = request.user;
      const { videoUrl, audioUrl, chatId } = z.object({
        videoUrl: z.string().url(),
        audioUrl: z.string().url(),
        chatId:   z.string().optional(),
      }).parse(request.body);

      // Только платные планы
      const userPlan = await prisma.user.findUnique({ where: { id: userId }, select: { plan: true } });
      if (userPlan?.plan === 'FREE') {
        return reply.code(403).send({ error: 'Генерация провалась, попробуйте позже', code: 'PLAN_RESTRICTED' });
      }

      // Rate limit (1/мин)
      if (!await checkVideoRateLimit(userId)) {
        return reply.code(429).send({ error: 'Слишком много запросов. Подождите минуту.', code: 'RATE_LIMITED' });
      }

      await checkResets(userId);

      // Deduct as standard 4s video
      try {
        await checkAndDeduct(userId, 'video_std_4s', 1);
      } catch (err: any) {
        return reply.code(403).send({ error: err.message, code: err.code ?? 'LIMIT_VIDEOS' });
      }

      let resultUrl: string;
      try {
        resultUrl = await generateLipSync(videoUrl, audioUrl);
      } catch (err: any) {
        await refundCaspers(userId, 'video_std_4s').catch(() => {});
        const userInfo = await prisma.user.findUnique({ where: { id: userId }, select: { name: true } }).catch(() => null);
        notifyApiError({
          userId,
          userName: userInfo?.name,
          operation: 'video_gen',
          error: err.message,
          context: 'lipsync',
        }).catch(() => {});
        return reply.code(502).send({ error: 'Генерация провалась, попробуйте позже' });
      }

      if (chatId) {
        await prisma.message.create({
          data: { chatId, userId, role: 'assistant', content: encrypt('lip sync'), mode: 'reel', tokensCost: 0, mediaUrl: resultUrl },
        }).catch(() => {});
      }

      return { mediaUrl: resultUrl };
    },
  });

  // ── Job status ────────────────────────────────────────────────────────────
  fastify.get('/generate/:jobId', {
    preHandler: [fastify.authenticate],
    handler: async (request, reply) => {
      const { userId } = request.user;
      const { jobId } = request.params as { jobId: string };

      const job = await prisma.generateJob.findFirst({
        where: { id: jobId, userId },
      });

      if (!job) return reply.code(404).send({ error: 'Job not found' });

      return {
        id: job.id,
        status: job.status,
        mode: job.mode,
        prompt: job.prompt,
        mediaUrl: job.mediaUrl,
        error: job.error ? 'Генерация провалась, попробуйте позже' : null,
        createdAt: job.createdAt,
        updatedAt: job.updatedAt,
      };
    },
  });

  // ── User jobs list ────────────────────────────────────────────────────────
  fastify.get('/generate', {
    preHandler: [fastify.authenticate],
    handler: async (request) => {
      const { userId } = request.user;
      const query = request.query as { mode?: string; page?: string };
      const page = parseInt(query.page ?? '1');

      const jobs = await prisma.generateJob.findMany({
        where: {
          userId,
          ...(query.mode ? { mode: query.mode } : {}),
        },
        orderBy: { createdAt: 'desc' },
        skip: (page - 1) * 20,
        take: 20,
      });

      return { jobs };
    },
  });
}
